terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

# -----------------------------------------------------------------------------
# Everything here except groq_api_key is generated by Terraform, not
# supplied — jwt_access_secret and internal_service_key are symmetric
# secrets nothing outside this system needs to know, and the per-service DB
# passwords replace database/docker/init/03-roles.sql's fixed local dev
# passwords ('dev_auth' etc.) with real random ones.
#
# IMPORTANT — this only creates the Secrets Manager entries. It does NOT
# create the database roles themselves: `CREATE ROLE auth_service_role LOGIN
# PASSWORD '<generated>'` (one per db_service_roles entry) still has to run
# against the real RDS instance, using these generated passwords, before any
# Lambda can actually connect as that role. RDS has no docker-entrypoint-
# initdb.d equivalent, and RDS is not publicly accessible, so this is a
# manual (or CI-run-from-inside-the-VPC) one-time step — see the "Data"
# section of the deployment plan for how to reach it (SSM port-forwarding is
# simplest, no bastion host to maintain).
# -----------------------------------------------------------------------------

locals {
  tags = {
    Project     = var.project_name
    Environment = var.environment
  }
}

resource "random_password" "jwt_access_secret" {
  length  = 48
  special = false
}

resource "random_password" "internal_service_key" {
  length  = 48
  special = false
}

# special = false: this ends up inside a postgresql:// connection string —
# special characters would need URL-encoding there, not worth the risk.
resource "random_password" "db" {
  for_each = toset(var.db_service_roles)
  length   = 32
  special  = false
}

resource "aws_secretsmanager_secret" "jwt_access_secret" {
  name = "${var.project_name}/${var.environment}/jwt-access-secret"
  tags = local.tags
}

resource "aws_secretsmanager_secret_version" "jwt_access_secret" {
  secret_id     = aws_secretsmanager_secret.jwt_access_secret.id
  secret_string = random_password.jwt_access_secret.result
}

resource "aws_secretsmanager_secret" "internal_service_key" {
  name = "${var.project_name}/${var.environment}/internal-service-key"
  tags = local.tags
}

resource "aws_secretsmanager_secret_version" "internal_service_key" {
  secret_id     = aws_secretsmanager_secret.internal_service_key.id
  secret_string = random_password.internal_service_key.result
}

resource "aws_secretsmanager_secret" "groq_api_key" {
  name = "${var.project_name}/${var.environment}/groq-api-key"
  tags = local.tags
}

resource "aws_secretsmanager_secret_version" "groq_api_key" {
  secret_id     = aws_secretsmanager_secret.groq_api_key.id
  secret_string = var.groq_api_key
}

resource "aws_secretsmanager_secret" "db_password" {
  for_each = toset(var.db_service_roles)
  name     = "${var.project_name}/${var.environment}/db/${each.key}-service-role-password"
  tags     = local.tags
}

resource "aws_secretsmanager_secret_version" "db_password" {
  for_each  = toset(var.db_service_roles)
  secret_id = aws_secretsmanager_secret.db_password[each.key].id

  # RDS Proxy's SECRETS auth scheme reads the role to authenticate as FROM
  # this JSON shape ({username, password}) — a bare password string (what
  # this held before) isn't enough for the proxy to know which role it's
  # even trying to log in as. The Lambda env vars are unaffected: they read
  # random_password.db[...].result directly, not this secret's content.
  secret_string = jsonencode({
    username = "${each.key}_service_role"
    password = random_password.db[each.key].result
  })
}

output "jwt_access_secret_arn" {
  value = aws_secretsmanager_secret.jwt_access_secret.arn
}

output "jwt_access_secret_value" {
  value     = random_password.jwt_access_secret.result
  sensitive = true
}

output "internal_service_key_arn" {
  value = aws_secretsmanager_secret.internal_service_key.arn
}

output "internal_service_key_value" {
  value     = random_password.internal_service_key.result
  sensitive = true
}

output "groq_api_key_arn" {
  value = aws_secretsmanager_secret.groq_api_key.arn
}

output "db_service_role_arns" {
  description = "Map of service name -> that role's password secret ARN"
  value       = { for k, v in aws_secretsmanager_secret.db_password : k => v.arn }
}

output "db_service_role_passwords" {
  description = "Map of service name -> generated password, for building each Lambda's DATABASE_URL and for the one-time CREATE ROLE step"
  value       = { for k, v in random_password.db : k => v.result }
  sensitive   = true
}
